# Copyright (c) Mathias Kaerlev, Somer Hayter and Julien Kross 2013.
#
# This file is part of cuwo.
#
# cuwo is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cuwo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cuwo.  If not, see <http://www.gnu.org/licenses/>.

SOUNDS = [
    'hit',
    'blade1',
    'blade2',
    'long-blade1',
    'long-blade2',
    'hit1',
    'hit2',
    'punch1',
    'punch2',
    'hit-arrow',
    'hit-arrow-critical',
    'smash1',
    'slam-ground',
    'smash-hit2',
    'smash-jump',
    'swing',
    'shield-swing',
    'swing-slow',
    'swing-slow2',
    'arrow-destroy',
    'blade1',
    'punch2',
    'salvo2',
    'sword-hit03',
    'block',
    'shield-slam',
    'roll',
    'destroy2',
    'cry',
    'levelup2',
    'missioncomplete',
    'water-splash01',
    'step2',
    'step-water',
    'step-water2',
    'step-water3',
    'channel2',
    'channel-hit',
    'fireball',
    'fire-hit',
    'magic02',
    'watersplash',
    'watersplash-hit',
    'lich-scream',
    'drink2',
    'pickup',
    'disenchant2',
    'upgrade2',
    'swirl',
    'human-voice01',
    'human-voice02',
    'gate',
    'spike-trap',
    'fire-trap',
    'lever',
    'charge2',
    'magic02',
    'drop',
    'drop-coin',
    'drop-item',
    'male-groan',
    'female-groan',
    'male-groan',
    'female-groan',
    'goblin-male-groan',
    'goblin-female-groan',
    'lizard-male-groan',
    'lizard-female-groan',
    'dwarf-male-groan',
    'dwarf-female-groan',
    'orc-male-groan',
    'orc-female-groan',
    'undead-male-groan',
    'undead-female-groan',
    'frogman-male-groan',
    'frogman-female-groan',
    'monster-groan',
    'troll-groan',
    'mole-groan',
    'slime-groan',
    'zombie-groan',
    'Explosion',
    'punch2',
    'menu-open2',
    'menu-close2',
    'menu-select',
    'menu-tab',
    'menu-grab-item',
    'menu-drop-item',
    'craft',
    'craft-proc',
    'absorb',
    'manashield',
    'bulwark',
    'bird1',
    'bird2',
    'bird3',
    'cricket1',
    'cricket2',
    'owl1',
    'owl2'
]
